package com.gmail.a.e.tsvetkov.driver;

import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

public class AConnection implements Connection {
    private final BConnectionLink link;

    public AConnection(String host) {
        this.link = new BConnectionLink();
    }

    @Override
    public Statement createStatement() {
        return new AStatement(link);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) {
        return null;
    }

    @Override
    public CallableStatement prepareCall(String sql) {
        return null;
    }

    @Override
    public String nativeSQL(String sql) throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public boolean getAutoCommit() {
        return false;
    }

    @Override
    public void setAutoCommit(boolean autoCommit) {

    }

    @Override
    public void commit() {

    }

    @Override
    public void rollback() throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public void close() {

    }

    @Override
    public boolean isClosed() {
        return false;
    }

    @Override
    public DatabaseMetaData getMetaData() {
        return null;
    }

    @Override
    public boolean isReadOnly() {
        return false;
    }

    @Override
    public void setReadOnly(boolean readOnly) throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public String getCatalog() throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public void setCatalog(String catalog) throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public int getTransactionIsolation() throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public void setTransactionIsolation(int level) throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public SQLWarning getWarnings() {
        return null;
    }

    @Override
    public void clearWarnings() {

    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) {
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) {
        return null;
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) {
        return null;
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) {
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) {
        return null;
    }

    @Override
    public Map<String, Class<?>> getTypeMap() throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public int getHoldability() throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public void setHoldability(int holdability) throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public Savepoint setSavepoint() throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public Savepoint setSavepoint(String name) throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public void rollback(Savepoint savepoint) throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public void releaseSavepoint(Savepoint savepoint) throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) {
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) {
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) {
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) {
        return null;
    }

    @Override
    public Clob createClob() throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public Blob createBlob() throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public NClob createNClob() throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public SQLXML createSQLXML() throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public boolean isValid(int timeout) {
        return true;
    }

    @Override
    public void setClientInfo(String name, String value) {

    }

    @Override
    public String getClientInfo(String name) {
        return null;
    }

    @Override
    public Properties getClientInfo() {
        return null;
    }

    @Override
    public void setClientInfo(Properties properties) {

    }

    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public String getSchema() throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public void setSchema(String schema) throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public void abort(Executor executor) throws SQLException {
        throw new NotSuportedException();
    }

    @Override
    public void setNetworkTimeout(Executor executor, int milliseconds) {

    }

    @Override
    public int getNetworkTimeout() {
        return 0;
    }

    @Override
    public <T> T unwrap(Class<T> iface) {
        return null;
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) {
        return false;
    }

    private class NotSuportedException extends SQLException {
    }
}
